# Generated by Django 3.1.1 on 2020-10-11 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donateto', models.CharField(choices=[('red cross', 'RED CROSS'), ('non-profit #1', 'NON-PROFIT #1'), ('non-profit #2', 'NON-PROFIT #2')], default='red cross', max_length=30)),
                ('amount', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=350)),
            ],
        ),
    ]
