# Generated by Django 3.1.1 on 2020-10-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdollars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donateto',
            field=models.CharField(choices=[('red cross', 'Red Cross'), ('non-profit #1', 'Non-profit #1'), ('non-profit #2', 'Non-profit #2')], default='red cross', max_length=30),
        ),
    ]
