# Generated by Django 3.1.1 on 2020-11-14 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microdollars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='donateto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='microdollars.organizationmodel', verbose_name='Organization'),
        ),
    ]
