# Generated by Django 3.1.1 on 2020-10-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdollars', '0003_auto_20201011_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=100)),
                ('about_me', models.TextField(default='INFO ON THIS ORGANIZATION', max_length=1000)),
            ],
        ),
    ]
