# Generated by Django 3.1.1 on 2020-10-23 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdollars', '0005_auto_20201014_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmodel',
            name='image',
            field=models.ImageField(default='/static/microdollars/missing.png', upload_to='myimages'),
        ),
    ]
