# Generated by Django 3.1.1 on 2020-11-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microdollars', '0006_organizationmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='donation',
            name='comment',
            field=models.CharField(blank=True, max_length=350),
        ),
    ]
